import type { MaterialSummary } from "@/types/materials";

export const MOCK_MATERIALS: MaterialSummary[] = [
  {
    material_id: "mp-149",
    formula_pretty: "Si",
    elements: ["Si"],
    nelements: 1,
    nsites: 2,
    energy_above_hull: 0,
    formation_energy_per_atom: -5.424,
    density: 2.33,
    volume: 40.89,
    band_gap: 1.12,
    total_magnetization: 0,
    theoretical: false,
    is_stable: true,
    symmetry: {
      crystal_system: "cubic",
      symbol: "Fd-3m",
      point_group: "m-3m",
    },
    has_props: ["electronic_structure", "total_energy"],
    last_updated: "2024-11-01T00:00:00Z",
  },
  {
    material_id: "mp-19017",
    formula_pretty: "LiFePO4",
    elements: ["Li", "Fe", "P", "O"],
    nelements: 4,
    nsites: 28,
    energy_above_hull: 0.001,
    formation_energy_per_atom: -5.776,
    density: 3.45,
    volume: 291.4,
    band_gap: 0.76,
    total_magnetization: 3.8,
    theoretical: false,
    is_stable: true,
    symmetry: {
      crystal_system: "orthorhombic",
      symbol: "Pnma",
      point_group: "mmm",
    },
    has_props: ["electronic_structure", "dielectric"],
    last_updated: "2024-09-18T00:00:00Z",
  },
  {
    material_id: "mp-1143",
    formula_pretty: "Al2O3",
    elements: ["Al", "O"],
    nelements: 2,
    nsites: 10,
    energy_above_hull: 0,
    formation_energy_per_atom: -3.266,
    density: 3.98,
    volume: 137.1,
    band_gap: 5.83,
    total_magnetization: 0,
    theoretical: false,
    is_stable: true,
    symmetry: {
      crystal_system: "trigonal",
      symbol: "R-3c",
      point_group: "-3m",
    },
    has_props: ["electronic_structure", "elasticity"],
    last_updated: "2024-08-05T00:00:00Z",
  },
];
